version: '3'

services:
  goravel:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - goravel-net
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goravel_db
      MYSQL_USER: goravel_user
      MYSQL_PASSWORD: goravel_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goravel-net

  # app:
  #   build: .
  #   container_name: goravel_app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
  #   networks:
  #     - goravel-net

volumes:
  mysql_data:

networks:
  goravel-net: